### ISSUE TITLE
Joystick support

### ISSUE THREAD

**Issue by maci0** [jdolan/quake2world#35]
Add joystick support.

Changed 15 months ago by wickedshell

    owner changed from jdolan to wickedshell
    status changed from new to assigned

Changed 13 months ago by maci

do we really need joystick/gamepad support ???
Changed 13 months ago by wickedshell

Might be nice in the end. I'm not working on it till post 4/1 beta stuff though. (Or at least I'm not planning to).

**Comment by jdolan** [comment]
We're not going to do this in the foreseeable future.

**Comment by maci0** [comment]
I don't really see the use-case either. Unless we plan to expand to the console market (steam machines ?)
