### ISSUE TITLE
Dedicated server crash

### ISSUE THREAD

**Issue by jar3817** [jdolan/quake2world#81]
From the logs, nobody even joined the server, it just crashes randomly if it sits there long enough. This is using commit # 2034 (20898b1d3be2c3b374aa2fdb864ef838c2d1c0d5)

Here is the "backtrace" spit out to STDOUT and a gdb backtrace too:

======= Backtrace: =========
/lib/libc.so.6(+0x70df1)[0x4e5df1]
/lib/libc.so.6(+0x73531)[0x4e8531]
/home/quake/q2w/bin/quake2world[0x805775a]
/home/quake/q2w/bin/quake2world(Mem_Free+0x53)[0x80578a3]
/lib/libglib-2.0.so.0(g_list_foreach+0x30)[0x2b0da0]
======= Memory map: ========
00110000-0012e000 r-xp 00000000 fc:01 4627       /lib/ld-2.12.so
0012e000-0012f000 r--p 0001d000 fc:01 4627       /lib/ld-2.12.so
0012f000-00130000 rw-p 0001e000 fc:01 4627       /lib/ld-2.12.so
00130000-00131000 r-xp 00000000 00:00 0          [vdso]
00131000-00150000 r-xp 00000000 fc:01 21956      /usr/local/lib/libphysfs.so.2.0.3
00150000-00152000 rw-p 0001e000 fc:01 21956      /usr/local/lib/libphysfs.so.2.0.3
00152000-00164000 r-xp 00000000 fc:01 4971       /lib/libz.so.1.2.3
00164000-00165000 r--p 00011000 fc:01 4971       /lib/libz.so.1.2.3
00165000-00166000 rw-p 00012000 fc:01 4971       /lib/libz.so.1.2.3
00166000-00188000 r-xp 00000000 fc:01 4952       /lib/libncurses.so.5.7
00188000-00189000 rw-p 00021000 fc:01 4952       /lib/libncurses.so.5.7
00189000-00268000 r-xp 00000000 fc:01 5406       /usr/lib/libstdc++.so.6.0.13
00268000-0026c000 r--p 000de000 fc:01 5406       /usr/lib/libstdc++.so.6.0.13
0026c000-0026d000 rw-p 000e2000 fc:01 5406       /usr/lib/libstdc++.so.6.0.13
0026d000-00274000 rw-p 00000000 00:00 0
00274000-0038c000 r-xp 00000000 fc:01 5302       /lib/libglib-2.0.so.0.2800.8
0038c000-0038d000 rw-p 00118000 fc:01 5302       /lib/libglib-2.0.so.0.2800.8
0038d000-003fe000 r-xp 00000000 fc:01 21968      /usr/lib/libSDL-1.2.so.0.11.4
003fe000-003ff000 rw-p 00071000 fc:01 21968      /usr/lib/libSDL-1.2.so.0.11.4
003ff000-0042b000 rw-p 00000000 00:00 0
0042b000-00453000 r-xp 00000000 fc:01 4642       /lib/libm-2.12.so
00453000-00454000 r--p 00027000 fc:01 4642       /lib/libm-2.12.so
00454000-00455000 rw-p 00028000 fc:01 4642       /lib/libm-2.12.so
00455000-00458000 r-xp 00000000 fc:01 4640       /lib/libdl-2.12.so
00458000-00459000 r--p 00002000 fc:01 4640       /lib/libdl-2.12.so
00459000-0045a000 rw-p 00003000 fc:01 4640       /lib/libdl-2.12.so
0045a000-00471000 r-xp 00000000 fc:01 4658       /lib/libpthread-2.12.so
00471000-00472000 r--p 00016000 fc:01 4658       /lib/libpthread-2.12.so
00472000-00473000 rw-p 00017000 fc:01 4658       /lib/libpthread-2.12.so
00473000-00475000 rw-p 00000000 00:00 0
00475000-00605000 r-xp 00000000 fc:01 4634       /lib/libc-2.12.so
00605000-00606000 ---p 00190000 fc:01 4634       /lib/libc-2.12.so
00606000-00608000 r--p 00190000 fc:01 4634       /lib/libc-2.12.so
00608000-00609000 rw-p 00192000 fc:01 4634       /lib/libc-2.12.so
00609000-0060c000 rw-p 00000000 00:00 0
0060c000-00622000 r-xp 00000000 fc:01 4956       /lib/libtinfo.so.5.7
00622000-00625000 rw-p 00015000 fc:01 4956       /lib/libtinfo.so.5.7
00625000-00642000 r-xp 00000000 fc:01 17883      /lib/libgcc_s-4.4.7-20120601.so.1
00642000-00643000 rw-p 0001d000 fc:01 17883      /lib/libgcc_s-4.4.7-20120601.so.1
00643000-0064a000 r-xp 00000000 fc:01 4662       /lib/librt-2.12.so
0064a000-0064b000 r--p 00006000 fc:01 4662       /lib/librt-2.12.so
0064b000-0064c000 rw-p 00007000 fc:01 4662       /lib/librt-2.12.so
0064c000-00658000 r-xp 00000000 fc:01 4650       /lib/libnss_files-2.12.so
00658000-00659000 r--p 0000b000 fc:01 4650       /lib/libnss_files-2.12.so
00659000-0065a000 rw-p 0000c000 fc:01 4650       /lib/libnss_files-2.12.so
0065a000-0065f000 r-xp 00000000 fc:01 4648       /lib/libnss_dns-2.12.so
0065f000-00660000 r--p 00004000 fc:01 4648       /lib/libnss_dns-2.12.so
00660000-00661000 rw-p 00005000 fc:01 4648       /lib/libnss_dns-2.12.so
00661000-00676000 r-xp 00000000 fc:01 4660       /lib/libresolv-2.12.so
00676000-00677000 ---p 00015000 fc:01 4660       /lib/libresolv-2.12.so
00677000-00678000 r--p 00015000 fc:01 4660       /lib/libresolv-2.12.so
00678000-00679000 rw-p 00016000 fc:01 4660       /lib/libresolv-2.12.so
00679000-0067b000 rw-p 00000000 00:00 0
0067b000-006a6000 r-xp 00000000 fc:01 140711     /home/quake/q2w/lib/quake2world/default/game.so (deleted)
006a6000-006a8000 rw-p 0002a000 fc:01 140711     /home/quake/q2w/lib/quake2world/default/game.so (deleted)
006a8000-006e9000 rw-p 00000000 00:00 0
006e9000-00817000 r-xp 00000000 fc:01 138135     /usr/lib/mysql/libmysqlclient.so.16.0.0
00817000-0085f000 rw-p 0012d000 fc:01 138135     /usr/lib/mysql/libmysqlclient.so.16.0.0
0085f000-00866000 r-xp 00000000 fc:01 4638       /lib/libcrypt-2.12.so
00866000-00867000 r--p 00007000 fc:01 4638       /lib/libcrypt-2.12.so
00867000-00868000 rw-p 00008000 fc:01 4638       /lib/libcrypt-2.12.so
00868000-0088f000 rw-p 00000000 00:00 0
0088f000-008a6000 r-xp 00000000 fc:01 4644       /lib/libnsl-2.12.so
008a6000-008a7000 r--p 00016000 fc:01 4644       /lib/libnsl-2.12.so
008a7000-008a8000 rw-p 00017000 fc:01 4644       /lib/libnsl-2.12.so
008a8000-008aa000 rw-p 00000000 00:00 0
008aa000-008fe000 r-xp 00000000 fc:01 8457       /usr/lib/libssl.so.1.0.0
008fe000-00900000 r--p 00054000 fc:01 8457       /usr/lib/libssl.so.1.0.0
00900000-00903000 rw-p 00056000 fc:01 8457       /usr/lib/libssl.so.1.0.0
00903000-00a78000 r-xp 00000000 fc:01 8455       /usr/lib/libcrypto.so.1.0.0
00a78000-00a79000 ---p 00175000 fc:01 8455       /usr/lib/libcrypto.so.1.0.0
00a79000-00a87000 r--p 00175000 fc:01 8455       /usr/lib/libcrypto.so.1.0.0
00a87000-00a8d000 rw-p 00183000 fc:01 8455       /usr/lib/libcrypto.so.1.0.0
00a8d000-00a90000 rw-p 00000000 00:00 0
00a90000-00adf000 r-xp 00000000 fc:01 4029       /lib/libfreebl3.so
00adf000-00ae0000 r--p 0004e000 fc:01 4029       /lib/libfreebl3.so
00ae0000-00ae1000 rw-p 0004f000 fc:01 4029       /lib/libfreebl3.so
00ae1000-00ae5000 rw-p 00000000 00:00 0
00ae5000-00b23000 r-xp 00000000 fc:01 6167       /lib/libgssapi_krb5.so.2.2
00b23000-00b24000 r--p 0003e000 fc:01 6167       /lib/libgssapi_krb5.so.2.2
00b24000-00b25000 rw-p 0003f000 fc:01 6167       /lib/libgssapi_krb5.so.2.2
00b25000-00bfb000 r-xp 00000000 fc:01 6173       /lib/libkrb5.so.3.3
00bfb000-00c01000 r--p 000d5000 fc:01 6173       /lib/libkrb5.so.3.3
00c01000-00c02000 rw-p 000db000 fc:01 6173       /lib/libkrb5.so.3.3
00c02000-00c05000 r-xp 00000000 fc:01 5224       /lib/libcom_err.so.2.1
00c05000-00c06000 r--p 00002000 fc:01 5224       /lib/libcom_err.so.2.1
00c06000-00c07000 rw-p 00003000 fc:01 5224       /lib/libcom_err.so.2.1
00c07000-00c2f000 r-xp 00000000 fc:01 6171       /lib/libk5crypto.so.3.1
00c2f000-00c30000 r--p 00028000 fc:01 6171       /lib/libk5crypto.so.3.1
00c30000-00c31000 rw-p 00029000 fc:01 6171       /lib/libk5crypto.so.3.1
00c31000-00c32000 rw-p 00000000 00:00 0
00c32000-00c3c000 r-xp 00000000 fc:01 6175       /lib/libkrb5support.so.0.1
00c3c000-00c3d000 r--p 00009000 fc:01 6175       /lib/libkrb5support.so.0.1
00c3d000-00c3e000 rw-p 0000a000 fc:01 6175       /lib/libkrb5support.so.0.1
00c3e000-00c40000 r-xp 00000000 fc:01 6163       /lib/libkeyutils.so.1.3
00c40000-00c41000 r--p 00001000 fc:01 6163       /lib/libkeyutils.so.1.3
00c41000-00c42000 rw-p 00002000 fc:01 6163       /lib/libkeyutils.so.1.3
00c42000-00c5f000 r-xp 00000000 fc:01 4026       /lib/libselinux.so.1
00c5f000-00c60000 r--p 0001c000 fc:01 4026       /lib/libselinux.so.1
00c60000-00c61000 rw-p 0001d000 fc:01 4026       /lib/libselinux.so.1
08048000-08067000 r-xp 00000000 fc:01 140719     /home/quake/q2w/bin/quake2world
08067000-08068000 rw-p 0001f000 fc:01 140719     /home/quake/q2w/bin/quake2world
08068000-08bed000 rw-p 00000000 00:00 0          [heap]
b555d000-b57ee000 rw-p 00000000 00:00 0
b57ee000-b57ef000 ---p 00000000 00:00 0
b57ef000-b61ef000 rw-p 00000000 00:00 0
b61ef000-b61f0000 ---p 00000000 00:00 0
b61f0000-b6bf0000 rw-p 00000000 00:00 0
b6bf0000-b6bf1000 ---p 00000000 00:00 0
b6bf1000-b75f1000 rw-p 00000000 00:00 0
b75f1000-b75f2000 ---p 00000000 00:00 0
b75f2000-b7ff7000 rw-p 00000000 00:00 0
b7fff000-b8000000 rw-p 00000000 00:00 0
bffeb000-c0000000 rw-p 00000000 00:00 0          [stack]
^M
Program received signal SIGABRT, Aborted.
0x00130424 in __kernel_vsyscall ()
Missing separate debuginfos, use: debuginfo-install glib2-2.28.8-1.fc15.i686 glibc-2.12-1.107.el6_4.5.i686 keyutils-libs-1.4-4.el6.i686 krb5-libs-1.10.3-10.el6_4.6.i686 libcom_err-1.41.12-14.el6_4.4.i686 libgcc-4.4.7-3.el6.i686 libselinux-2.0.94-5.3.el6_4.1.i686 libstdc++-4.4.7-3.el6.i686 mysql-libs-5.1.69-1.el6_4.i686 ncurses-libs-5.7-3.20090208.el6.i686 nss-softokn-freebl-3.14.3-3.el6_4.i686 openssl-1.0.0-27.el6_4.2.i686 zlib-1.2.3-29.el6.i686
(gdb)

(gdb) backtrace
#0  0x00130424 in __kernel_vsyscall ()
#1  0x0049fad1 in raise () from /lib/libc.so.6
#2  0x004a13aa in abort () from /lib/libc.so.6
#3  0x004df995 in __libc_message () from /lib/libc.so.6
#4  0x004e5df1 in malloc_printerr () from /lib/libc.so.6
#5  0x004e8531 in _int_free () from /lib/libc.so.6
#6  0x0805775a in Mem_Free_ (b=0x8bd0f08) at mem.c:78
#7  0x080578a3 in Mem_Free (p=0x8bd0f1c) at mem.c:96
#8  0x002b0da0 in g_list_foreach () from /lib/libglib-2.0.so.0
#9  0x002b0de3 in g_list_free_full () from /lib/libglib-2.0.so.0
#10 0x0804ebfe in Sv_SendClientMessages () at sv_send.c:508
#11 0x0804d781 in Sv_Frame (msec=1) at sv_main.c:830
#12 0x0804b324 in Frame (argc=6, argv=0xbffff7e4) at main.c:231
#13 main (argc=6, argv=0xbffff7e4) at main.c:293
(gdb)

**Comment by jdolan** [comment]
Any update on this @jar3817 ?

**Comment by jar3817** [comment]
Haven't seen any problems lately, looks fixed.
