### ISSUE TITLE
Hud disappears and jitter on respawn when connected to remote server

### ISSUE THREAD

**Issue by jar3817** [jdolan/quake2world#82]
Doesn't happen locally, but when connected to remote server. Respawning after getting fragged or typing "kill" will cause the HUD to flicker and eventually disappear. The player view also sometimes jitters up and down after respawn too. Crouching once usually fixes the jitter.  

Happens with 64bit win7 and 32bit win8 clients on linux server. Not sure about other client operating systems.

**Comment by jdolan** [comment]
@jar3817 I think 1070055825d67a6e973a243d427cfc1ba6856354 actually fixes this. Can you try to reproduce this at some point soon?

**Comment by jar3817** [comment]
I'll check this out tonight. ...
