### ISSUE TITLE
Out of date documentation

### ISSUE THREAD

**Issue by kwadroke** [jdolan/quake2world#93]
While working on a Vagrantfile for compiling Q2W, I noticed that the information for building for Linux is out of date with the current source code on this page:
http://quake2world.net/books/documentation/developing-and-modding/source-code-and-dependencies
(Mostly SDL2 stuff)

This too has some out of date information
http://quake2world.net/books/documentation/installation-and-maintenance

I know this is more for the website than the code itself. I tried to post it twice on the website's forums, but I saw an error and my post was not submitted.
warning: Creating default object from empty value in /var/www/quake2world.net/modules/forum/forum.module on line 219.

**Comment by jdolan** [comment]
Hi,

Thanks for the info! I'd be interested to see your Vagrant setup when it's ready, too. Are you compiling it on Debian or something else? Are you hoping to make a dedicated server distributable build?

**Comment by kwadroke** [comment]
Right now I'm compiling it for Ubuntu, but, will probably create a new one for Debian (and maybe Windows)
Here's my current Vagrantfile: https://github.com/kwadroke/linux-scripts/blob/master/vagrant/quake2world/Vagrantfile
I jump between PCs fairly often so I wanted to be able to put together a build/test environment quickly without a lot of work. I'm just starting to work with Vagrant, so I figured this would also get me up to speed with it.

**Comment by jdolan** [comment]
Yea, Vagrant is awesome. Ubuntu is also a fine choice -- I'm sure it's the most popular among our Linux players. For Windows, I would assume you're looking to cross compile? We haven't actually supported native Windows builds in a few years. @maci0 has put together excellent XC scripts that we use to target Win32 from Fedora. Take a peek in the `win32` directory in this repo.

Thanks again, and if you're interested in hacking on the project, please let me know as I would _love_ to have some help.

**Comment by kwadroke** [comment]
I switched from Ubuntu to Debian a few releases ago, but, there were other projects using Ubuntu for their Vagrant builds. Haven't put together a Debian one yet.
I've been away from Q2W for a while and haven't looked at building for Windows since before the switch from SVN. 
I might try to put together some additions in the Vagrantfile for cross compiling for Windows sometime in the not too distant future.

**Comment by jdolan** [comment]
Docs updated. @kwadroke how did you make out with your build VM?

**Comment by kwadroke** [comment]
I've switched it over to Debian for my build VM. Here's the link:
https://github.com/kwadroke/linux-scripts/blob/master/vagrant/quake2world/Vagrantfile.debian-x86

**Comment by jdolan** [comment]
That's awesome. @maci0 what do you think of providing a Vagrantfile for the Fedora cross-compile VM? That'd be so handy.
